// Object containing General Hiragana transliterations, kana, and translations.
var general_hiragana = [

    // Articles
    {translation: "The", kana:"その", transliteration:"Sono", type: "General Hiragana"},

    // Nouns
    {translation: "Rabbit", kana:"うさぎ", transliteration:"Usagi", type: "General Hiragana"},
    {translation: "Bear", kana:"くま", transliteration:"Kuma", type: "General Hiragana"},
    {translation: "Fox", kana:"きっね", transliteration:"Kitsune", type: "General Hiragana"},
    {translation: "Weasel", kana:"はち", transliteration:"Hachi", type: "General Hiragana"},
    {translation: "Tiger", kana:"とら", transliteration:"Tora", type: "General Hiragana"},
    {translation: "Honey", kana:"はちみっ", transliteration:"Hachimitsu", type: "General Hiragana"},
    {translation: "Country", kana:"こく", transliteration:"Koku", type: "General Hiragana"},
    {translation: "Foreign-Country", kana:"がいこく", transliteration:"Gaikoku", type: "General Hiragana"},
    {translation: "Hand", kana:"て", transliteration:"Te", type: "General Hiragana"},
    {translation: "Empty-Hand", kana:"からて", transliteration:"Karate", type: "General Hiragana"},
    {translation: "Sword-Path", kana:"けんど", transliteration:"Kendo", type: "General Hiragana"},
    {translation: "Sword-Way", kana:"けんど", transliteration:"Kendo", type: "General Hiragana"},
    {translation: "Warrior", kana:"ぶし", transliteration:"Bushi", type: "General Hiragana"},
    {translation: "Wood", kana:"ぼく", transliteration:"Boku", type: "General Hiragana"},
    {translation: "Wooden-Sword", kana:"ぼけん", transliteration:"Boken", type: "General Hiragana"},
    {translation: "Sword", kana:"けん", transliteration:"Ken", type: "General Hiragana"},
    {translation: "Warrior-Path", kana:"ぶしど", transliteration:"Bushido", type: "General Hiragana"},
    {translation: "Warrior-Way", kana:"ぶしど", transliteration:"Bushido", type: "General Hiragana"},
    {translation: "War-Path", kana:"ぶど", transliteration:"Budo", type: "General Hiragana"},
    {translation: "War-Way", kana:"ぶど", transliteration:"Budo", type: "General Hiragana"},
    {translation: "War", kana:"ぶ", transliteration:"Bu", type: "General Hiragana"},
    {translation: "Path", kana:"ど", transliteration:"Do", type: "General Hiragana"},
    {translation: "Way", kana:"ど", transliteration:"Do", type: "General Hiragana"},
    {translation: "Sword-Master", kana:"けんせい", transliteration:"Kensei", type: "General Hiragana"},
    {translation: "Sword-Saint", kana:"けんせい", transliteration:"Kensei", type: "General Hiragana"},
    {translation: "Throwing-Knife", kana:"すりけん", transliteration:"Shuriken", type: "General Hiragana"},
    {translation: "Knife", kana:"ないふ", transliteration:"Naifu", type: "General Hiragana"},
    {translation: "Servant", kana:"さむらい", transliteration:"Samurai", type: "General Hiragana"},
    {translation: "Town", kana:"まち", transliteration:"Machi", type: "General Hiragana"},
    {translation: "Spear", kana:"やり", transliteration:"Yari", type: "General Hiragana"},
    {translation: "Army-Commander", kana:"そぐん", transliteration:"Shogun", type: "General Hiragana"},
    {translation: "School", kana:"りゆ", transliteration:"Ryu", type: "General Hiragana"},
    {translation: "Masterless-Samurai", kana:"ろにん", transliteration:"Ronin", type: "General Hiragana"},
    {translation: "Spirit", kana:"き", transliteration:"Ki", type: "General Hiragana"},
    {translation: "Mind", kana:"かくご", transliteration:"Kakugo", type: "General Hiragana"},
    {translation: "Service", kana:"ほこ", transliteration:"Hoko", type: "General Hiragana"},
    {translation: "Councillor", kana:"かろ", transliteration:"Karo", type: "General Hiragana"},
    {translation: "Souvenir", kana:"みやげ", transliteration:"Miyage", type: "General Hiragana"},
    {translation: "Porridge", kana:"ぞすい", transliteration:"Zosui", type: "General Hiragana"},
    {translation: "Demon", kana:"おに", transliteration:"Oni", type: "General Hiragana"},
    {translation: "Duty", kana:"ぎり", transliteration:"Giri", type: "General Hiragana"},
    {translation: "Defilement", kana:"けがれ", transliteration:"Kegare", type: "General Hiragana"},
    {translation: "God", kana:"かみ", transliteration:"Kami", type: "General Hiragana"},
    {translation: "Car", kana:"さ", transliteration:"Sha", type: "General Hiragana"},
    {translation: "Foreign-Car", kana:"がいさ", transliteration:"Gaisha", type: "General Hiragana"},
    {translation: "Teacher", kana:"せんせい", transliteration:"Sensei", type: "General Hiragana"},
    {translation: "High-School", kana:"こおこお", transliteration:"Kookoo", type: "General Hiragana"},
    {translation: "Fan", kana:"うちわ", transliteration:"Uchiwa", type: "General Hiragana"},
    {translation: "Person", kana:"じん", transliteration:"Jin", type: "General Hiragana"},
    {translation: "Foreigner", kana:"がいじん", transliteration:"Gaijin", type: "General Hiragana"},
    {translation: "To-do", kana:"いたす", transliteration:"Itasu", type: "General Hiragana"},

    // Pronouns
    {translation: "This", kana:"この", transliteration:"Kono", type: "General Hiragana"},
    {translation: "This", kana:"これ", transliteration:"Kore", type: "General Hiragana"},
    {translation: "That", kana:"ぁの", transliteration:"Ano", type: "General Hiragana"},
    {translation: "Which", kana:"どの", transliteration:"Dono", type: "General Hiragana"},
    {translation: "Everyone", kana:"みなさん", transliteration:"Minasan", type: "General Hiragana"},
    {translation: "You", kana:"どう", transliteration:"Dou", type: "General Hiragana"},

    // Verbs
    {translation: "Learn", kana:"まなぶ", transliteration:"Manabu", type: "General Hiragana"},
    {translation: "Be", kana:"なる", transliteration:"Naru", type: "General Hiragana"},
    {translation: "Welcome", kana:"いたしまして", transliteration:"Itashimashite", type: "General Hiragana"},

    // Adverbs
    {translation: "Out", kana:"でる", transliteration:"Deru", type: "General Hiragana"},
    {translation: "Very", kana:"ども", transliteration:"Domo", type: "General Hiragana"},
    {translation: "Yes", kana:"はい", transliteration:"Hai", type: "General Hiragana"},
    {translation: "No", kana:"ばんご", transliteration:"Bango", type: "General Hiragana"},
    {translation: "How", kana:"どう", transliteration:"Dou", type: "General Hiragana"},

    // Adjectives
    {translation: "Many", kana:"ども", transliteration:"Domo", type: "General Hiragana"},
    {translation: "Martial", kana:"ぶ", transliteration:"Bu", type: "General Hiragana"},
    {translation: "Wooden", kana:"ぼく", transliteration:"Boku", type: "General Hiragana"},
    {translation: "Improved", kana:"かい", transliteration:"Kai", type: "General Hiragana"},
    {translation: "Difficult", kana:"かたい", transliteration:"Katai", type: "General Hiragana"},
    {translation: "Foreign", kana:"がい", transliteration:"Gai", type: "General Hiragana"},

    // Interjections
    {translation: "Hello", kana:"こんにちわ", transliteration:"Konnichiwa", type: "General Hiragana"},
    {translation: "Goodbye", kana:"さよむら", transliteration:"Sayonara", type: "General Hiragana"},
    {translation: "Thanks", kana:"ありがと", transliteration:"Arigato", type: "General Hiragana"},
    {translation: "Thank-You", kana:"ありがと", transliteration:"Arigato", type: "General Hiragana"},
    {translation: "Good-Evening", kana:"こんばんわ", transliteration:"Konbanwa", type: "General Hiragana"},
    {translation: "Good-Afternoon", kana:"こんにちわん", transliteration:"Konnichiwan", type: "General Hiragana"},
    {translation: "You're Welcome", kana:"どう-いたしまして", transliteration:"Dou-Itashimashite", type: "General Hiragana"},

    // Prepositions
    {translation: "Of", kana:"の", transliteration:"No", type: "General Hiragana"},
    {translation: "At", kana:"の", transliteration:"No", type: "General Hiragana"},
    {translation: "What", kana:"なに", transliteration:"Nani", type: "General Hiragana"},
];